<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [
            [
                'name'=>'user-create',
                'guard_name'=>'web',
            ],
            [
                'name'=>'user-edit',
                'guard_name'=>'web',
            ],
            [
                'name'=>'user-show',
                'guard_name'=>'web',
            ],
            [
                'name'=>'user-update',
                'guard_name'=>'web',
            ],
            [
                'name'=>'user-delete',
                'guard_name'=>'web',
            ],
            [
                'name'=>'ticket-create',
                'guard_name'=>'web',
            ],
            [
                'name'=>'ticket-edit-update',
                'guard_name'=>'web',
            ],
            [
                'name'=>'ticket-view',
                'guard_name'=>'web',
            ],
            [
                'name'=>'ticket-delete',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-team-create',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-team-edit-update',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-team-view',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-team-delete',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-complain-type-create',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-complain-type-edit-update',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-complain-type-view',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-complain-type-delete',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-solution-create',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-solution-edit-update',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-solution-view',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-solution-delete',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-complain-source-create',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-complain-source-edit-update',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-complain-source-view',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-complain-source-delete',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-client-send-email',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-client-send-sms',
                'guard_name'=>'web',
            ],
            [
                'name'=>'client-link-search',
                'guard_name'=>'web',
            ],
            [
                'name'=>'user-search',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-ticket-remark-create',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-ticket-accept',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-ticket-reopen',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-ticket-close',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-ticket-super-close',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-ticket-handover',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-ticket-forward',
                'guard_name'=>'web',
            ],
            [
                'name'=>'support-ticket-team-search',
                'guard_name'=>'web',
            ],

        ];

        foreach($permissions as $permission){
            Permission::create($permission);
         }
    }
}
